---
- hosts: network
  connection: local
  gather_facts: no
  vars:
    cli:
      username: vagrant
      password: vagrant
  tasks:
    - name: run show version on remote devices
      eos_command:
        commands: show version
        provider: '{{ cli }}'
      register: result
    - debug: var=result
